/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#002203",
        "outline-variant": "var(--outline-variant)",
        "on-secondary-fixed": "#261900",
        "surface-tint": "#c3cb9a",
        "on-error": "#690005",
        "background": "var(--background)",
        "on-secondary-container": "#ffe0a8",
        "on-secondary": "#402d00",
        "secondary-container": "#836000",
        "surface-dim": "#14140d",
        "primary-fixed-dim": "#c3cb9a",
        "tertiary-fixed": "#a3f69a",
        "error": "#ffb4ab",
        "on-primary-fixed": "#181e01",
        "on-primary": "#2d3310",
        "surface-container-low": "var(--surface-container-low)",
        "on-tertiary-container": "#003206",
        "inverse-primary": "#5a623a",
        "surface-container": "var(--surface-container)",
        "outline": "#919285",
        "primary-fixed": "#dfe7b4",
        "primary-container": "#8d9568",
        "primary": "var(--primary)",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#36352e",
        "surface-bright": "#3a3932",
        "secondary-fixed-dim": "#eec060",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-primary-fixed-variant": "#434a25",
        "on-tertiary-fixed-variant": "#005310",
        "on-primary-container": "#262d0a",
        "on-surface": "var(--on-surface)",
        "tertiary": "#88d981",
        "surface": "var(--surface)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-background": "var(--on-background)",
        "on-secondary-fixed-variant": "#5c4200",
        "tertiary-container": "#53a250",
        "error-container": "#93000a",
        "inverse-surface": "#e6e2d7",
        "tertiary-fixed-dim": "#88d981",
        "secondary": "var(--secondary)",
        "inverse-on-surface": "#323129",
        "surface-variant": "#36352e",
        "on-tertiary": "#003908",
        "surface-container-high": "#2b2a23",
        "secondary-fixed": "#ffdea2"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "section-gap": "120px",
        "unit": "8px",
        "gutter": "24px",
        "container-max": "1280px"
      },
      fontFamily: {
        "body-lg": ["Syne", "sans-serif"],
        "display-lg": ["EB Garamond", "serif"],
        "ui-element": ["Syne", "sans-serif"],
        "headline-md": ["Syne", "sans-serif"],
        "headline-xl": ["Syne", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "body-md": ["Syne", "sans-serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        sans: ["Syne", "sans-serif"]
      }
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        figmaDark: {
          "color-scheme": "dark",
          "base-100": "#14140d",
          "base-200": "#1c1c15",
          "base-300": "#212019",
          "base-content": "#e6e2d7",
          "primary": "#c3cb9a",
          "primary-content": "#14140d",
          "secondary": "#eec060",
          "secondary-content": "#14140d",
          "accent": "#e6e2d7",
          "accent-content": "#14140d",
          "neutral": "#2b2a23",
          "neutral-content": "#e6e2d7",
          "info": "#3abff8",
          "info-content": "#14140d",
          "success": "#88d981",
          "success-content": "#14140d",
          "warning": "#eec060",
          "warning-content": "#14140d",
          "error": "#ffb4ab",
          "error-content": "#14140d",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.25rem",
          "--rounded-badge": "0.25rem",
          "--animation-btn": "0.2s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.25rem",
        },
        figmaLight: {
          "color-scheme": "light",
          "base-100": "#FAFAF6",
          "base-200": "#F1EFE6",
          "base-300": "#EAE7DA",
          "base-content": "#202514",
          "primary": "#5A633F",
          "primary-content": "#FAFAF6",
          "secondary": "#6A7051",
          "secondary-content": "#FAFAF6",
          "accent": "#202514",
          "accent-content": "#FAFAF6",
          "neutral": "#E1DFCF",
          "neutral-content": "#202514",
          "info": "#3abff8",
          "info-content": "#FAFAF6",
          "success": "#36d399",
          "success-content": "#FAFAF6",
          "warning": "#fbbd23",
          "warning-content": "#FAFAF6",
          "error": "#f87272",
          "error-content": "#FAFAF6",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.25rem",
          "--rounded-badge": "0.25rem",
          "--animation-btn": "0.2s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.25rem",
        }
      }
    ],
  },
}
